global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nextjs-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3000'] # Ubah jika pakai Cloud Run